name:                HL-Systems
version:             0.1.0.0
github:              "GaliMouette/HL-Systems"
license:             BSD3
author:              "GaliMouette"
maintainer:          "example@example.com"
copyright:           "2022 GaliMouette"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/GaliMouette/HL-Systems#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- gloss
- optparse-applicative

library:
  source-dirs: src

executables:
  L-Systems-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - L-Systems

tests:
  L-Systems-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - L-Systems
